### PR TITLE
Allow for arbitrary Pool configuration

### PR DESCRIPTION
**Pull request by mistercrunch**
I was looking for more flexibility around pools and this hook should
allow for users to pass whatever pool object they want to use.

### CODE REVIEW

**Comment by davidism** [comment]
Is this a duplicate / related to #333?

**Comment by mistercrunch** [comment]
This PR here may be more flexible as you can instantiate whatever pool object you want with whatever parameter.

**Comment by mistercrunch** [comment]
@davidism can we get this through? I think this PR is the most flexible as it allows users to pass whatever pool configuration they may want

**Comment by rsyring** [comment]
Thank you for your contribution and sorry this took so long. I believe #684 will solve this use case.

**Pull request closed without merging**
