### PR TITLE
Simplify chained comparison

### PR DESCRIPTION
**Pull request by MrKiven**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
travis failure relates to a py2.6 issue with sa, no OP#s code

**Comment by MrKiven** [comment]
can we merge it?

**Comment by rsyring** [comment]
Do we have sufficient test coverage of this code, especially edge cases, that we are confident the change doesn't break something that's not being tested?

**Comment by ThiefMaster** [comment]
All this PR changes is replacing `x < y and z > y` with the `x < y < z` shortcut, so this doesn't affect functionality.

However, I think wrapping in the middle of a comparison is awful and reduces readability - if this was on one line then I wouldn't mind this change, but the way it's formatted right now I think it's bad. So unless we raise the max line length to something higher not requiring wrapping here, I'm against merging this.

**Comment by davidism** [comment]
Closing because it's just shuffling logic around rather than fixing anything. At some point we'll consider code style more broadly.

**Pull request closed without merging**
