### PR TITLE
update app property of SQLAlchemy on init_app

### PR DESCRIPTION
**Pull request by matanw**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Please check the comments on one of the many closed PRs for the same thing. It's not set there on purpose.

**Comment by matanw** [comment]
> Please check the comments on one of the many closed PRs for the same thing. It's not set there on purpose.

Adding here a comment explaining this can be a good idea

**Comment by ThiefMaster** [comment]
You mean in the code? Indeed, that could be a good idea..

**Comment by matanw** [comment]
CR opened for comment: https://github.com/pallets/flask-sqlalchemy/pull/761

**Pull request closed without merging**
