### PR TITLE
Add flake8

### PR DESCRIPTION
**Pull request by rsyring**
refs #688 

This is just to show how little work was needed in the code to get flake8 passing.  If @davidism approves, I could add flake8 to CI and merge this.  I don't think it's impact on future PR requests will be that big.

### CODE REVIEW

**Comment by davidism** [comment]
Let's use Werkzeug's config, I'd like all projects to be consistent. Line length will be 88 to match Black's formatting. We use the flake8-bugbear extension as well for some checks.

**Comment by davidism** [comment]
The problem with adding CI for this is that any time you merge in an existing PR that doesn't conform, you break CI for all new PRs. The existing PRs don't have the CI config, so you don't see an error until the code you merged shows up in a PR that does have the CI config.

**Comment by rsyring** [comment]
> The problem with adding CI for this now is that any time you merge in an existing PR that doesn't conform, you break CI for all new PRs

I usually rebase PRs onto the existing branch before merging.

> This is why I generally like to wait until there are no open PRs

Given the number of open PRs even after I cleaned up what I could, and the small amount of time available to maintain this package, I'd rather not wait until all the open PRs are merged and just focus on fixing the PRs prior to merge.

> Or we can fully commit to the Pallets style now and apply the other pre-commit hooks like Black as well, with the understanding that we'll need to clean up existing PRs.

I've never needed anything more than flake8, so can't speak to the other tools.  If that means we get a style checker soon, then I'm for it.  :)

**Comment by davidism** [comment]
Going to close this since I'll be doing this along with a bunch of other style stuff when I add the pre-commit config from the other projects and drop Python 2.

**Pull request closed without merging**
