### PR TITLE
add comment about db.init_app

### PR DESCRIPTION
**Pull request by matanw**

### CODE REVIEW

**Comment by jab** [comment]
Sorry, just saw the context from #760.

**Comment by jab** [comment]
Updated previous comment.

**Comment by matanw** [comment]
I really don't understand what is going on. om my "temp2" commit, code exactly same to the master, why the checks are failed?

**Comment by ThiefMaster** [comment]
not related to your change

**Comment by matanw** [comment]
OK; my commit is ready. can anyone approve and merge it?

**Comment by jab** [comment]
Thank you for the contribution!

**Pull request merged**
